# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190920_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[(post.models.PostType('News Post'), 'News Post'), (post.models.PostType('Blog Post'), 'Blog Post')], default=post.models.PostType('Blog Post'), max_length=5),
        ),
    ]
