# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190920_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[(post.models.PostType('News Post'), 'News Post'), (post.models.PostType('Blog Post'), 'Blog Post')], default=post.models.PostType('Blog Post'), max_length=20),
        ),
    ]
