# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190921_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'News Post'), ('BLOG', 'Blog Post')], default=post.models.PostType('Blog Post'), max_length=20),
        ),
    ]
