# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-27 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Your comment'),
        ),
    ]
