# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='static/img/favicon.png', upload_to='profiles'),
        ),
    ]
