# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20190927_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.CharField(default='old@email.com', max_length=50),
            preserve_default=False,
        ),
    ]
